# Generated by Django 4.2.4 on 2026-02-14 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackagingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=50)),
                ('part_description', models.CharField(max_length=255)),
                ('packaging_type', models.CharField(choices=[('BOX', 'Box'), ('PALLET', 'Pallet'), ('CRATE', 'Crate')], max_length=20)),
                ('branding', models.CharField(choices=[('Brand1', 'Brand1'), ('Brand2', 'Brand2'), ('Brand3', 'Brand3')], max_length=20)),
                ('packaging_materials', models.CharField(max_length=255)),
                ('part_length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('part_width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('part_height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('part_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('drawing', models.FileField(blank=True, null=True, upload_to='drawings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='packagingapp.packagingcatalogue')),
            ],
            options={
                'unique_together': {('catalogue', 'part_number')},
            },
        ),
    ]
