# Generated by Django 4.2.4 on 2026-02-26 15:56

from django.db import migrations, models
import django.db.models.deletion
import packagingapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('packagingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_length', models.DecimalField(decimal_places=3, max_digits=12)),
                ('product_width', models.DecimalField(decimal_places=3, max_digits=12)),
                ('product_height', models.DecimalField(decimal_places=3, max_digits=12)),
                ('rotation_1', models.BooleanField(default=True)),
                ('rotation_2', models.BooleanField(default=False)),
                ('rotation_3', models.BooleanField(default=False)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('product_picture', models.ImageField(blank=True, null=True, upload_to=packagingapp.models.product_image_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='packagingapp.productcatalogue')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('catalogue', 'product_id')},
            },
        ),
    ]
