# Generated by Django 4.2.4 on 2026-02-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagingapp', '0002_productcatalogue_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desired_qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
