# Generated by Django 4.2.4 on 2026-03-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagingapp', '0003_product_desired_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagingmaterial',
            name='packaging_type',
            field=models.CharField(choices=[('BOX', 'Box'), ('PALLET', 'Pallet'), ('CRATE', 'Crate'), ('BAG', 'Bag')], max_length=20),
        ),
    ]
