# Generated by Django 4.2.4 on 2026-03-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagingapp', '0004_alter_packagingmaterial_packaging_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagingmaterial',
            name='packaging_type',
            field=models.CharField(choices=[('BOX', 'BOX'), ('PALLET', 'PALLET'), ('CRATE', 'CRATE'), ('BAG', 'BAG')], max_length=20),
        ),
    ]
