# Generated by Django 4.2.4 on 2026-03-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagingapp', '0005_alter_packagingmaterial_packaging_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagingcatalogue',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='catalogue_pictures/'),
        ),
        migrations.AddField(
            model_name='packagingmaterial',
            name='external_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='packagingmaterial',
            name='external_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='packagingmaterial',
            name='external_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='packagingmaterial',
            name='part_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
