# Generated by Django 4.2.4 on 2026-03-29 15:03

from django.db import migrations, models
import packagingapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('packagingapp', '0006_packagingcatalogue_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_volume',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='productcatalogue',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productcatalogue',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=packagingapp.models.product_catalogue_picture_upload_path),
        ),
    ]
